### ISSUE TITLE
关于登陆方法

### ISSUE THREAD

**Issue by Seeeeck** [yifanzheng/spring-security-jwt#3]
您好,我刚学Spring Security.我看到您在AuthService的authLogin方法中进行了SecurityContextHolder.getContext().setAuthentication(authentication);,我想问在登陆方法这样做是为什么,我认为只是一个登陆方法的话不需要设置authentication.我查阅资料,SecurityContextHolder是通过ThreadLocal实现的,当response返回出去后,这个authentication立刻会被Spring Security自动清除.所以这个设置看起来没什么意义.如果是我理解错了,希望您能告诉我,谢谢.

**Comment by yifanzheng** [comment]
@Seeeeck hi seeeeck，不好意思哈，今天才发现你的留言，之前也没有收到提醒。正如你说的那样，其实登录时可以不用设置  authentication。
