### ISSUE TITLE
master分支无法启动的问题

### ISSUE THREAD

**Issue by xstressr** [yifanzheng/spring-security-jwt#8]
您好，在你升级后swagger2.10.0版本后，原来的EnableSwagger2注解被禁用，取而代之的EnableSwagger2WebMvc，并需要添加spring-plugin-core的2.0.0.RELEASE版本，不知道我可不可以提交我的分支来完善这个版本，很感谢题主的项目给我一个spring security的很好学习案例

**Comment by yifanzheng** [comment]
> 您好，在你升级后swagger2.10.0版本后，原来的EnableSwagger2注解被禁用，取而代之的EnableSwagger2WebMvc，并需要添加spring-plugin-core的2.0.0.RELEASE版本，不知道我可不可以提交我的分支来完善这个版本，很感谢题主的项目给我一个spring security的很好学习案例

hi @xstressr 可以的，欢迎 pull request。
